version: "3.9"

services:
  app:
    build: .
    container_name: chapeira_back
    restart: always
    ports:
      - '3333:3333'
    expose:
      - '3333'
    environment:
      VIRTUAL_HOST: chapeira.wfbtecnologia.com.br
      LETSENCRYPT_HOST: chapeira.wfbtecnologia.com.br
      LETSENCRYPT_EMAIL: ettore.barbosa@gmail.com
    volumes:
      - .:/usr/app
    networks:
      - nginx-proxy
  nginx:
    container_name: nginx_chapeira
    ports:
      - "3333:80"
    expose:
      - "3333"
      - "443"
    environment:
      VIRTUAL_HOST: chapeira.wfbtecnologia.com.br
      LETSENCRYPT_HOST: chapeira.wfbtecnologia.com.br
      LETSENCRYPT_EMAIL: ettore.barbosa@gmail.com
    build: ./nginx-proxy
    volumes:
      - ./nginx-proxy
    networks:
      - nginx-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: "always"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - nginx-proxy
  nginx-proxy-letsencrypt:
    restart: "always"
    image: jrcs/letsencrypt-nginx-proxy-companion:2.1
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - nginx-proxy
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-conf:
  nginx-html:
  static_volume:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
