version: "3.9"

services:
  app:
    build: .
    working_dir: /usr/app
    container_name: chapeira_admin_back
    restart: always
    volumes:
      - .:/user/app
    ports:
      - "3333:333"
    networks:
      - app-networks

  nginx-proxy:
    container_name: server-nginx
    build: ./nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-networks

networks:
  app-networks:
    name: app-networks
