version: "3.9"

services:
  app:
    build: .
    working_dir: /usr/app
    container_name: chapeira_admin_back
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - .:/user/app
    environment:
      - VIRTUAL_HOST=chapeira.wfbtecnologia.com.br
      - VIRTUAL_PORT=3333
      - LETSENCRYPT_HOST=chapeira.wfbtecnologia.com.br
      - LETSENCRYPT_EMAIL=ettore.barbosa@gmail.com

networks:
  external:
    name: nginx-proxy
