version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    ports:
      - "3333:333"
    networks:
      - app-networks

  nginx-proxy:
    build: ./nginx-proxy
    container_name: container-lb
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-networks

networks:
  app-networks:
    name: app-networks
