version: "3.9"

services:
  nginx:
    container_name: registra-app-nginx
    ports:
      - "80:80"
    expose:
      - "8181"
      - "443"

    build: ./nginx-proxy
    networks:
      - nginx-proxy
  app:
    build: .
    working_dir: /usr/app
    container_name: chapeira_admin_back
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - .:/user/app
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
