version: "3.9"

services:
  app:
    build: .
    working_dir: /usr/app
    container_name: chapeira_admin_back
    restart: always
    volumes:
      - .:/user/app
    ports:
      - "3333:333"
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST= chapeira.wfbtecnologia
      - LETSENCRYPT_HOST= chapeira.wfbtecnologia
      - LETSENCRYPT_EMAIL= ettore.barbosa@gmail.com
    networks:
      - app-networks

  nginx:
    container_name: server-nginx
    restart: always
    build: ./nginx-proxy
    environment:
      - VIRTUAL_HOST= chapeira.wfbtecnologia
      - LETSENCRYPT_HOST= chapeira.wfbtecnologia
      - LETSENCRYPT_EMAIL= ettore.barbosa@gmail.com
    expose:
      - "80"
      - "443"
    networks:
      - app-networks

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-networks
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"

  letsencrypt_nginx_proxy_companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:rw"
    depends_on:
      - nginx_proxy
networks:
  app-networks:
    name: app-networks

volumes:
  nginx-conf:
  nginx-vhost:
  html:
  certs:
