version: "3.9"

services:
  app:
    build: .
    container_name: chapeira_back
    restart: always
    ports:
      - '3333:3333'
    expose:
      - '3333'
    volumes:
      - .:/usr/app
  nginx:
    container_name: nginx_chapeira
    expose:
      - "8080"
      - "443"
    ports:
      - 8080:80
    build: ./nginx-proxy
    volumes:
      - ./nginx-proxy
