version: "3.9"

services:
  app:
    build: .
    working_dir: /usr/app
    container_name: chapeira_admin_back
    restart: always
    volumes:
      - .:/user/app
    ports:
      - "3333:333"
    expose:
      - "80"
      - "443"
    enviroment:
      VIRTUAL_HOST: chapeira.wfbtecnologia
      LETSENCRYPT_HOST: chapeira.wfbtecnologia
      LETSENCRYPT_EMAIL: ettore.barbosa@gmail.com
    networks:
      - app-networks

  nginx:
    container_name: server-nginx
    build: ./nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    expose:
      - "80"
      - "443"
    enviroment:
      VIRTUAL_HOST: chapeira.wfbtecnologia
      LETSENCRYPT_HOST: chapeira.wfbtecnologia
      LETSENCRYPT_EMAIL: ettore.barbosa@gmail.com
    depends_on:
      - app
    networks:
      - app-networks

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: "always"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-conf:/etc/nginx/conf.d
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - app-networks
  nginx-proxy-letsencrypt:
    restart: "always"
    image: jrcs/letsencrypt-nginx-proxy-companion:2.1
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - app-networks

volumes:
  lumes:
  nginx-certs:
  nginx-vhost:
  nginx-conf:
  nginx-html:
  static_volume:

networks:
  app-networks:
    name: app-networks
