version: "3.9"

services:
  app:
    build: .
    container_name: chapeira_admin_back
    restart: always
    ports:
      - "3333:333"
    volumes:
      - .:/usr/app
    networks:
      - app-networks

  nginx-proxy:
    container_name: server-nginx
    build: ./nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-networks

networks:
  - app-networks
